Update lwt_ppx to 2.1.0
Earlier versions of lwt_ppx used in dream-mirage can conflict with the base ocaml version 4.08 required by dream.opam.

For example:
Fatal error: exception File "src/mirage/mirage.ml", line 389, characters 2-34: complex open are not supported before OCaml 4.08